Image sharer issue 1
AppFolioOnboarding/image-sharer-chris-mason pull request #1
Opened 2021-09-08 21:20 UTC by chris-mason

Closes #1

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-09-08 21:22 UTC, chris-mason commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 1: Development Environment](https://trello.com/c/DwaC2o9f/449-issue-1-development-environment)

2021-09-09 17:32 UTC, infiniteluke requested changes
One small issue. with a test in the second commit. Also can you run `rubocop` on the repo and ensure it passes? I don't think we ever did that.

2021-09-09 17:32 UTC, infiniteluke commented on test/controllers/application_controlller_test.rb
> +    assert_select 'h1', text: 'Hello Marc Jacobs'
This assertion will not pass with the current state of this commit. Ideally all commits pass their own tests and don't require future changes. We should either change the controller or this test to match

2021-09-09 18:40 UTC, chris-mason commented on test/controllers/application_controlller_test.rb
> +    assert_select 'h1', text: 'Hello Marc Jacobs'
Rubocop is good, I ran it and cleaned up anything that was marked. Also updated the test in the second commit so that it matches the controller.

2021-09-09 18:45 UTC, infiniteluke approved these changes

2021-09-09 19:22 UTC, merged