React issue 1
AppFolioOnboarding/image-sharer-chris-mason pull request #10
Opened 2021-09-14 20:28 UTC by chris-mason

Closes #1

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-09-14 20:28 UTC, chris-mason commented
![](https://github.trello.services/images/mini-trello-icon.png) [React Issue 1: Add Footer](https://trello.com/c/9dgfYHTn/447-react-issue-1-add-footer)

2021-09-15 19:06 UTC, infiniteluke requested changes

2021-09-15 19:06 UTC, infiniteluke commented on app/controllers/application_controller.rb
> +  def home; end
this change shouldn't live in this commit. it should live wherever the original change occured

2021-09-15 19:06 UTC, infiniteluke commented on app/javascript/image_sharing/components/App.js
> +// import 'bootstrap/dist/css/bootstrap.min.css';
we can delete this instead of commenting it out

2021-09-15 19:06 UTC, infiniteluke commented on app/javascript/image_sharing/components/AppForm.js
> +            <Input />
Take a look at https://reactstrap.github.io/components/form/#app. We need to tie these inputs to their label for accessibility purposes via `for` and `name`.

2021-09-15 23:09 UTC, merged