Image sharer issue 4
AppFolioOnboarding/image-sharer-chris-mason pull request #4
Opened 2021-09-10 18:48 UTC by chris-mason

Closes #4

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-09-10 18:52 UTC, chris-mason commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 4: Image Seeds](https://trello.com/c/PnRFg0kT/451-issue-4-image-seeds)

2021-09-10 21:51 UTC, infiniteluke approved these changes

2021-09-13 16:27 UTC, infiniteluke requested changes

2021-09-13 16:27 UTC, infiniteluke commented on app/models/image.rb
> +require 'faraday'
remove me

2021-09-13 17:34 UTC, infiniteluke approved these changes

2021-09-13 17:34 UTC, merged