Image sharer issue 5
AppFolioOnboarding/image-sharer-chris-mason pull request #5
Opened 2021-09-10 21:43 UTC by chris-mason

Closes #5

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-09-10 21:43 UTC, chris-mason commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 5: Image Tags](https://trello.com/c/I94RBxPT/452-issue-5-image-tags)

2021-09-13 16:31 UTC, infiniteluke requested changes
A couple changes need. Also, ensure you read the docs on n+1 because I think it's likely that you're querying for each images tags separately.

2021-09-13 16:31 UTC, infiniteluke commented on db/seeds.rb
> +  Image.create url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/#{value.to_s.rjust 3, '0'}.png"
this shouldn't be in issue 5. you may need to rebase on issue 4 and drop this commit

2021-09-13 16:31 UTC, infiniteluke commented on db/seeds.rb
> -
we don't want to make style changes that are unrelated to the commit.

2021-09-13 16:31 UTC, infiniteluke commented on app/views/application/home.html.erb
> +          <h3>Tags: <%= image.tag_list %></h3>
this is likely causing an n+1 query unless you're including the tags for each image int he controller already

2021-09-13 17:48 UTC, chris-mason commented
Rebased with master and resolved commit history after strange git issues where PR #4 didn't get automatically rebased;

2021-09-13 17:49 UTC, chris-mason commented on db/seeds.rb
> +  Image.create url: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/#{value.to_s.rjust 3, '0'}.png"
Rebased and removed

2021-09-13 17:50 UTC, chris-mason commented on db/seeds.rb
> -
Rebased and removed

2021-09-13 18:39 UTC, chris-mason commented on app/views/application/home.html.erb
> +          <h3>Tags: <%= image.tag_list %></h3>
Updated the reference here; Can't use tag list as it still performs duplicate SQL queries even when performing eager loading using "includes"; Updated reference to .tags and issue appears to be resolved

2021-09-14 18:05 UTC, infiniteluke approved these changes

2021-09-14 23:41 UTC, merged