Image sharer issue 7
AppFolioOnboarding/image-sharer-chris-mason pull request #9
Opened 2021-09-13 23:59 UTC by chris-mason

Closes #7

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-09-14 00:02 UTC, chris-mason commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 7: Delete Image](https://trello.com/c/RZxmLSJ5/454-issue-7-delete-image)

2021-09-15 19:01 UTC, infiniteluke requested changes

2021-09-15 19:01 UTC, infiniteluke commented on app/controllers/images_controller.rb
> +    Image.find_by(id: params[:id])&.destroy
what happens if the image isn't found? we should handle that gracefully with a flash message

2021-09-15 19:01 UTC, infiniteluke commented on app/views/application/home.html.erb
> +            <%= button_to "Delete Image", "/images/#{image.id}", { method: "delete", data: { confirm: "Are you sure you wish to delete this image?" } } %>
this might prove hard to handle when you add handling for a missing image. `link_to` may be better. You can try for yourself

2021-09-16 17:49 UTC, infiniteluke approved these changes

2021-09-16 22:15 UTC, merged